mysite/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    # post views
    # path('', views.post_list, name='post_list'),
    # path('', views.PostListView.as_view(), name="post_list"),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>', views.post_deatil, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share')
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog'))
]

mysite/blog/models.py
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User
from django.db import models
from taggit.managers import TaggableManager


# Create your models here.

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset() \
            .filter(status='published')


class Post(models.Model):
    # 用于页面上的选择框标签，需要先提供一个二维的二元元组，第一个元素表示存在数据库内真实的值，第二个表示页面上显示的具体内容
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published')
    )
    title = models.CharField(max_length=256)
    slug = models.SlugField(max_length=256, unique_for_date='publish')  # what is unique_for_date
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name='blog_posts')  # 外键 关联User表 在创建多对一的关系的,需要在Foreign的第二参数中加入on_delete=models.CASCADE 删除主表数据的时候 这个也一起删除
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)  # 会在model对象第一次被创建时，将字段的值设置为创建时的时间，以后修改对象时，字段的值不会再更新
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
    tags = TaggableManager()

    # manager
    objects = models.Manager()  # the default manager
    published = PublishedManager()  # our custom manager

    class Meta:
        ordering = ('-publish',)  # - 表示降序

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.publish.year, self.publish.month, self.publish.day, self.slug])


class Comment(models.Model):
    # post.comments.all() 可以通过主表查询子表信息 即返回所有该post的评论; comment.post 可以获取该评论对应的post
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)  # 谁评论
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

mysite/blog/forms.py
from django import forms
from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)

class CommentForm(forms.ModelForm):
    """
        To create a form from a model, you just need to indicate which model to use to build
        the form in the Meta class of the form. Django introspects the model and builds the
        form dynamically for you.
    """
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

mysite/blog/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from django.core.mail import send_mail
from .forms import EmailPostForm, CommentForm
from .models import Post
from taggit.models import Tag


# Create your views here.

# def post_list(req):
#     posts = Post.published.all()
#     return render(req, 'blog/post/list.html', {'posts': posts})
def post_list(req, tag_slug=None):
    object_list = Post.published.all()
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    # 3 posts in each page
    paginator = Paginator(object_list, 3)
    page = req.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # if page is not an integer
        posts = paginator.page(1)
    except EmptyPage:
        # if page is out of range
        posts = paginator.page(paginator.num_pages)
    return render(req, 'blog/post/list.html', {'page': page, 'posts': posts, 'tag': tag})


def post_deatil(req, year, month, day, post):
    post = get_object_or_404(Post, slug=post, status='published', publish__year=year, publish__month=month,
                             publish__day=day)
    # list of active comments for this post
    comments = post.comments.filter(active=True)  # 利用外键

    new_comment = None
    comment_form = None

    if req.method == 'POST':
        # a comment was posted
        comment_form = CommentForm(data=req.POST)
        if comment_form.is_valid():
            # create comment object but dont save db yet
            new_comment = comment_form.save(commit=False)
            # assign the current post to the comment
            new_comment.post = post
            # save commit to the db
            new_comment.save()
        else:
            comment_form = CommentForm()
    return render(req, 'blog/post/detail.html', {'post': post, 'comments': comments, 'new_comment': new_comment,
                                                 'comment_form': comment_form})


# def post_share(req, post_id):
#     # retrieve post by id
#     post = get_object_or_404(Post, id=post_id, status='published')
#     if req.method == 'Post':
#         # form was submitted
#         form = EmailPostForm(req.POST)
#         if form.is_valid():
#             # form fields passed validation
#             cd = form.cleaned_data
#             # ... send email
#     else:
#         form = EmailPostForm()
#     return render(req, 'blog/post/share.html', {'post': post, 'form': form})

def post_share(req, post_id):
    # retrieve post by id
    post = get_object_or_404(Post, id=post_id, status='published')
    send = False
    if req.method == 'POST':  # 错误的：if req.method == 'Post'  要大写！！！POST！！！
        # form was submitted
        form = EmailPostForm(req.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = req.build_absolute_uri(post.get_absolute_url())  # 是uri！！！而不是url....
            subject = f"Django Test: {cd['name']} recommends you read " \
                      f"{post.title}"
            message = f"Read {post.title} at {post_url} \n\n" \
                      f"{cd['name']}\'s comments:{cd['comments']}"
            send_status = send_mail(subject, message, 'leety589589@163.com', [cd['to']], fail_silently=False)
            print('send_status', send_status)
        send = True
    else:
        form = EmailPostForm()
    return render(req, 'blog/post/share.html', {'post': post, 'form': form, 'send': send})


# def send_email(req):
#     # 目前好像没啥用
#     send_mail(
#         subject='Title',
#         message='This is a text from django',
#         from_email='leety589589@163.com',
#         recipient_list=['1091349400@qq.com'],
#         fail_silently=False
#     )
#     return HttpResponse('Ok')


class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'

mysite/blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link href = "{% static "blog.css" %}" rel="stylesheet">
</head>
<body>
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
    <div id="sidebar">
        <h2>My blog</h2>
        <p>This is my blog</p>
    </div>
</body>
</html>

mysite/blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
    <h1>{{ post.title }}</h1>
    <p class="date">
        Published {{ post.publish }} by {{ post.author }}
    </p>
    {{ post.body | linebreaks }}
    <p>
        <a href="{% url "blog:post_share" post.id %}">
            Share this post
        </a>
    </p>
    {% with comments.count as total_comments %}
        <h2>
            {{ total_comments }} comment{{ total_comments | pluralize }}
        </h2>
    {% endwith %}
    {% for comment in comments %}
        <div class="comment">
            <p class="info">
                Comment {{ forloop.counter }} by {{ comment.name }} {{ comment.created }}
            </p>
            {{ comment.body | linebreaks }}
        </div>
        {% empty %}
        <p>There are no comments yet</p>
    {% endfor %}
    {% if new_comment %}
        <h2>Your comment has been added.</h2>
    {% else %}
        <h2>Add a new comment</h2>
        <form method="post">
            {{ comment_form.as_p }}
            {% csrf_token %}
            <p><input type="submit" value="Add comment"></p>
        </form>
    {% endif %}
{% endblock %}

mysite/blog/templates/blog/post/list.html
{% extends "blog/base.html" %}

{% block title %} My blog {% endblock %}

{% block content %}
    <h1>My blog</h1>
    {% for post in posts %}
        <h2>
            <a href="{{ post.get_absolute_url }}">
                {{ post.title }}
            </a>
        </h2>
        <p class="tags">Tags: {{ post.tags.all|join:", " }}</p>
        <p class="date">
            Published {{ post.publish }} by {{ post.author }}
        </p>
        {{ post.body | truncatechars:30 | linebreaks }}
    {% endfor %}
    {% include "pagination.html" with page=page_obj %}
{% endblock %}

mysite/blog/templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %}Share a post{% endblock %}

{% block content %}
    {% if send %}
        <h1>E-mail successfully</h1>
        <p>
            "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.
        </p>
    {% else %}
        <h1>Share "{{ post.title }}" by e-mail</h1>
        <form method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" value="Send e-mail">
        </form>
    {% endif %}
{% endblock %}

mysite/blog/templates/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}
        <span class="current">
        Page {{ page.number }} of {{ page.paginator.num_pages }}
        </span>
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>